prescription.d/geogebra.sh

GeoGebra - это многоплатформенное динамическое математическое программное                                                
обеспечение для всех уровней образования. уровней образования, которое                                                   
объединяет геометрию, алгебру, таблицы, построение графиков, статистику                                                  
и вычисления в одном простом в использовании пакете. Она получила несколько                                              
наград в области образовательного программного обеспечения в Европе и США.                                               
Краткие факты:                                                                                                           
- Графики, алгебра и таблицы связаны и полностью динамичны …

add epm play geogebra

---

play.d/brave.sh
repack.d/brave-browser-beta.sh
repack.d/brave-browser.sh

* install stable build by default
* fix Conflicts $SPEC for beta and nightly repack.d
* add  repack.d/brave-browser.sh

epm play brave: install stable branch by default

---

play.d/snap4arduino.sh
repack.d/snap4arduino.sh

Added snap4arduino support for epm play.

epm play: add snap4arduino support

---

play.d/draw.io.sh
repack.d/draw.io.sh

https://github.com/jgraph/drawio-desktop

epm play: add draw.io support

---

play.d/sublime.sh

from /download link now to /download_thanks

epm play: fix sublime download link

---

play.d/vinteo.desktop.sh
repack.d/vinteo.desktop.sh

https://vinteo.com/en/vinteo-solutions/vinteo-desktop
https://download.vinteo.com/VinteoClient/linux/

epm play: add vinteo.desktop support

---

repack.d/common.sh
repack.d/jetbrains-toolbox.sh
repack.d/pycharm-professional.sh
repack.d/realvnc-vnc-server.sh
repack.d/realvnc-vnc-viewer.sh
repack.d/sane-panakvs.sh
repack.d/spotify-client.sh
repack.d/zoom.sh

* epm play common.sh: show list requires and provides
* epm play common.sh: get all library provides
* epm play zoom: fix broken deps

epm play: update common.sh and zoom

---

repack.d/plk-sane.sh

Tested on PLK_SANE_2.1.84-23323_RHEL-7.2_X86_64/plk-sane-2.1.84-23323.x86_64.rpm

epm repack: add support for plk-sane

---

prescription.d/switch-to-nvidia.sh

Добавление параметров для работы с wayland и двумя видеокартами

Update switch-to-nvidia.sh. Добавляем параметры загрузки

---

prescription.d/switch-to-nvidia.sh

* исправлен вывод переменной USED_KFLAVOUR в терминал
* добавлена проверка на добавление аргументов в grub (исправляет дубляжи если запускать с аргументом force)
* бэкап конфига grub создается только при условии изменения в конфиге

epmp switch-to-nvidia.sh: minor fixes

---

prescription.d/i586-fix.sh

Added: libgamemodeauto0, vkBasalt, mangohud

Update epm play i586-fix: Added: libgamemodeauto0, vkBasalt, mangohud

---

pack.d/davinci-resolve.sh

Not fully done yet. TODO: add fix for desktop files.

epm pack: add davinchi-resolve

---

pack.d/postman.sh
play.d/postman.sh
repack.d/postman.sh

epm pack: add postman

---

prescription.d/switch-to-nvidia.sh

- remove libGLUT and  libGLU
- translate output console into English

Remove packages, translate output console into English in switch-to-nvidia.sh

---

play.d/trezor-suite.sh
repack.d/Trezor-Suite.sh

https://trezor.io/trezor-suite
https://github.com/trezor/trezor-suite

epm play: add Trezor Suite

---

play.d/anilibrix.sh

Десктопный аниме-кинотеатр Анилибрии

epm play: add Anilibria (AniLibrix) desktop anime cinema

---

bash_completion/eepm

bash_completion update

---

pack.d/ayugram.sh
play.d/ayugram.sh
repack.d/ayugram.sh

знаю, что на альте есть сборка в сизифе и p11, но это только альт, а это в теории будет работать везде. бинарник качаю с собственного форка, они сами не собирают под линукс, только инструкция есть

epm play: add ayugram

---

pack.d/zwcad-viewer.sh
play.d/zwcad-viewer.sh

zwcad устанавливается и запускается, но файлы открыть не может, буду разбираться.

epm play: add zwcad-viewer (eterbug #17529)

---

bin/epm
bin/epm-install

epm-install: use sandbox as root, fix --force-overwrite option

---

play.d/min.sh
repack.d/min.sh

I tried to add Min browser mostly as of interest, to explore how epm play works. I don't really know how to build and package electron based application, so I got stuck at repack script. Would really love to get some help!

epm play: add min browser

---

repack.d/common.sh

This reverts commit ab6ab074e9065a3499a50fd31628ff307af14dbd. (fixed get_libs_requires)

Revert "get_libs_requires: avoid libs spam (eterbug #17815)"

---

repack.d/nekoray.sh

https://bugzilla.altlinux.org/52228

epm play: nekoray: fix icon

---

repack.d/winbox.sh

Using a new original icon instead of an old exe-application

epm play winbox: use new original icon
